### ISSUE TITLE
Coordinating Questionnaire Return and Answer record creation

### ISSUE THREAD

**Issue by kevinv11n** [barryhughes1/pluralSightQuestionnaires_LWCs#5]
On https://github.com/barryhughes1/pluralSightQuestionnaires_LWCs/wiki/33.-The-Problem:-Saving-an-Answer-BEFORE-saving-the-Return a solution is provided that coordinates record creation between the `Questionnaire Return` and `Answer` records. The solution entails significant coordination between parent and children components.

Instead consider "pulling up" all data needs to the parent, or even to a data manager component above the parent, that handles all data CRUD. By centralizing the data management the coordination of prerequisites (sequencing) of record creation will become much easier: the logic will be colocated, a single state machine can be created, and so forth.

**Comment by barryhughes1** [comment]
Thanks for the feedback @kevinv11n - it is appreciated. I will re-visit the repo code and instructions in the wiki and let you know when updated.

**Comment by barryhughes1** [comment]
@kevinv11n - In your comment above, I take the point that there are a number of options here - including, as you say, pushing up the answer object to the parent and saving them both in a function in the parent component. This would be a better more production ready solution for the scenario.

However, there are 2 points to be considered here:

1. If the parent component contained more than 1 type of child record - having the saving events contained within the component where the LDS is contained would allow for a lot more flexibility and ensure there would not be further editing of a parent component due to changes in child components.
2. The idea of the repo and course here is to explain how component communication and component lifecycle functions are coded and this seemed like a good example to explain these concepts.

**Comment by kevinv11n** [comment]
A pattern I've seen work well is to have a single data manager component at the "root" of your tree of components and then "presentation" components beneath it. These presentation components receive their data via `@api`, not `@wire`, which allows the data manager component to control what data is provided and when.

With this pattern the presentation components must event to their parent to request data changes.  The parent then executes the change and provisions new values down.

This is done in the [lwc-todomvc](https://github.com/salesforce/lwc-todomvc) project between `todo-app`  (the root and data manager) and `todo-item` (presentation component).  See https://github.com/salesforce/lwc-todomvc/blob/master/src/todo/app/app.html#L19-L26 for how data is passed to children and listening to mutation request events, https://github.com/salesforce/lwc-todomvc/blob/master/src/todo/item/item.js#L5-L6 for where values are received, and https://github.com/salesforce/lwc-todomvc/blob/master/src/todo/item/item.js#L21-L27 for how a mutation is requested.

**Comment by barryhughes1** [comment]
@kevinv11n - many thanks for your input and I agree with you that there are other patterns.

I feel my code is designed to explain the LWC component lifecycle and give a working example of these.
